# Generated by Django 3.2.6 on 2021-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='crated',
            new_name='created',
        ),
    ]
